language: node_js
before_install:
node_js:
  - "8"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
       ubuntu-toolchain-r-test
    packages:
      - g++-4.8
sudo: false
cache:
  npm: true
  directories:
    - node_modules
    - .jest-cache
script:
  - npm test
